server:
  port: 8021
spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:mysql://localhost:3306/tb_stock?characterEncoding=utf-8&useSSL=false
    username: root
    password: cheng123
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
mybatis:
  configuration:
    map-underscore-to-camel-case: true
