server:
  port: 8011
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/tb_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: cheng123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
