spring:
  datasource:
    url: jdbc:mysql://mysql.default:3306/tb_product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service.stockmgr.svc.cluster.local:8080/eureka
