spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: cheng123
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
