server:
  port: 8018
spring:
  profiles:
    active: dev
  application:
   name: product-client
ribbon:
  eureka:
    enabled: true
#eureka:
#  instance:
#   prefer-ip-address: false
#  client:
#   register-with-eureka: true
#  #下面一定要写 true
#   fetch-registry: true
#   initial-instance-info-replication-interval-seconds: 10
#   registry-fetch-interval-seconds: 5
#   service-url:
#    defaultZone: http://localhost:8080/eureka




